[project]
name = "advent-of-code-2025"
dynamic = ["version"]
requires-python = ">= 3.14"
readme = "README.md"
license = "UNLICENSE"
dependencies = [
  "pytest",
  "ruff>=0.14.7",
  "ty>=0.0.1a32",
]

[tool.ruff]
lint.select = ["I"]
